/**
 * The script inside the .app bundle.
 *
 * A TUI needs a terminal, so the bundle's job is to open one dedicated window
 * and run autodj in it — never a tab in whatever window happens to be in front,
 * which is the thing that makes the session impossible to find again.
 *
 * Relaunching while it is already running raises the existing window instead of
 * starting a second radio, so clicking the Dock icon behaves the way clicking
 * any other app's does.
 */

/**
 * AppleScript: open a new iTerm2 window running the command, remember it.
 *
 * The command goes to `create window ... command` rather than being typed into
 * the session afterwards. Writing text into a freshly created session races the
 * shell's startup and is silently swallowed when it loses.
 */
const itermScript = (command, idFile) => `
  tell application "iTerm"
    set newWindow to (create window with default profile command ${JSON.stringify(command)})
    tell current session of newWindow to set name to "AutoDJ"
    activate
    do shell script "echo " & (id of newWindow) & " > ${idFile}"
  end tell
`;

/** AppleScript: raise the window we opened last time, if it still exists. */
const itermFocus = (idFile) => `
  set windowId to (do shell script "cat ${idFile} 2>/dev/null || echo none")
  if windowId is not "none" then
    tell application "iTerm"
      repeat with w in windows
        if (id of w as string) is windowId then
          select w
          activate
          return "focused"
        end if
      end repeat
    end tell
  end if
  return "missing"
`;

/** Terminal.app equivalent, for a machine without iTerm2. */
const terminalScript = (command) => `
  tell application "Terminal"
    do script ${JSON.stringify(command)}
    set custom title of front window to "AutoDJ"
    activate
  end tell
`;

/**
 * Build the launcher.
 *
 * node and the CLI entry point are named by absolute path, because a
 * GUI-launched app inherits a bare PATH and would find neither through the
 * user's shell profile. They still run inside a *login* shell, since mpv and
 * yt-dlp are found on the PATH that profile sets up.
 */
export function launcherScript({ node, entry, idFile, shell = '/bin/zsh' }) {
  const inner = `exec ${quote(node)} ${quote(entry)}`;
  const command = `${shell} -lc ${quote(inner)}`;

  return `#!/bin/sh
# Generated by \`autodj app\`. Re-run that command to update it.
set -e

ID_FILE=${JSON.stringify(idFile)}

# Already playing? Raise that window rather than starting a second radio.
if pgrep -f ${JSON.stringify(entry)} > /dev/null 2>&1; then
  if [ -d /Applications/iTerm.app ]; then
    result=$(osascript -e ${shellQuote(itermFocus(idFile))} 2>/dev/null || echo missing)
    [ "$result" = "focused" ] && exit 0
  else
    osascript -e 'tell application "Terminal" to activate' >/dev/null 2>&1 && exit 0
  fi
fi

if [ -d /Applications/iTerm.app ]; then
  osascript -e ${shellQuote(itermScript(command, idFile))} > /dev/null
else
  osascript -e ${shellQuote(terminalScript(command))} > /dev/null
fi
`;
}

/** Single-quote for a shell, escaping any embedded quote. */
function quote(text) {
  return `'${text.replace(/'/g, `'\\''`)}'`;
}

const shellQuote = quote;
